/*
Problem Statement:
Alan Turing, the mathematician, is trying to break the encrypted messages of the German Troops, 
generated by their encryption device "Enigma". To find the distribution of characters, 
he needs to find out how many times a particular character appears in a string. 
But, to feed the data into his computer, "Christopher", he needs the data in lexicographic order, 
that is, in alphabetical order. Since, he is busy making "Christopher" better, he asks you for help. 
Help Alan find the frequency of characters in the encrypted strings in alphabetical order. 
The string contains only lower case alphabets.


Input:
The first line contains N, the length of the string, and the next line contains the string itself.
1 <= N<=100

Output
For each unique character in the string, 
print the character along with its frequency in the encrypted string, 
separated by '-' , on a new line.

Sample Input:
4
aman

Sample Output:
a-2
m-1
n-1
*/

function runProgram(input) {
  input = input.trim().split("\n");
  let size = +input[0];
  let str = input[1].trim().split("");

  AlanFreq(size, str);
}

function AlanFreq(size, str) {
  let obj = {};
  str.sort();

  for (let i = 0; i < size; i++) {
    //   let char = " ";
    let char = str[i];
    if (obj[char] === undefined) {
      obj[char] = 1;
    } else {
      obj[char]++;
    }
  }
  for (let key in obj) {
    {
      console.log(key + "-" + obj[key]);
    }
  }
}

if (process.env.USER === "") {
  runProgram(``);
} else {
  process.stdin.resume();
  process.stdin.setEncoding("ascii");
  let read = "";
  process.stdin.on("data", function (input) {
    read += input;
  });
  process.stdin.on("end", function () {
    read = read.replace(/\n$/, "");
    read = read.replace(/\n$/, "");
    runProgram(read);
  });
  process.on("SIGINT", function () {
    read = read.replace(/\n$/, "");
    runProgram(read);
    process.exit(0);
  });
}
